### ISSUE TITLE
Kirim token di dApps

### ISSUE THREAD

**Issue by RubberArchind** [jajanjawa/wvex#1]
Halo, saya lagi cari" referensi soal dapps vexanium dan nemu repo ini, udah nyoba code ngirim token versi dapps mobile dari repo ini, muncul tombol buat sign tapi gak ilang" tetep muncul buat signing terus. 

apakah punya solusi/pengalaman soal itu? terimakasih

**Comment by jajanjawa** [comment]
halaman kirim2.html bisa untuk token dengan 4 decimal

**Comment by RubberArchind** [comment]
bagian serialNumbernya sama untuk semua case atau gimana ya?

**Comment by jajanjawa** [comment]
percobaan saya terakhir kali pakai pocket.vex.min.js hasilnya error. 
yaitu yang pakai pe.pushActions(data).

gunakan halaman kirim2.html
itu juga bisa dipakai di vexwallet mobile
